### ISSUE TITLE
Add flexibility for advanced users to specify x-axis limits when plotting

### ISSUE THREAD

**Issue by shaziaruybal** [mrc-ide/DRpower#35]
Add a parameter eg `specify_x_axis = TRUE` to the functions `plot_prevalence()` and `plot_ICC()` so that the user can specify the x-axis limits (i.e., for better visibility), but the default will still be `prev_range` and `ICC_range` (i.e., `c(0,1)`)

- `plot_prevalence()`: https://github.com/mrc-ide/DRpower/blob/250c08a6aa457c5b5a0be099b315fd1523f27970/R/plot.R#L100
- `plot_ICC()`: https://github.com/mrc-ide/DRpower/blob/250c08a6aa457c5b5a0be099b315fd1523f27970/R/plot.R#L172

**Comment by bobverity** [comment]
Just looked into this and realized we already have this functionality!

Arguments are `prev_range` and `ICC-range` in the plotting functions.
